artifacts_root: artifacts

Data_ingestion:
  dir: artifacts/Data_ingestion
  url:  https://universe.roboflow.com/ds/UTS3XTkOad?key=RfyjEUb2vy
  local_folder: artifacts/Data_ingestion/data.zip
  unzip_folder: artifacts/Data_ingestion/data

Base_model:
  dir: artifacts/base_model
  base_model_path: artifacts/base_model/model.h5
  update_base_model_path: artifacts/base_model/model_update.h5

Model_Train:
  dir: model
  model_path: artifacts/model_train/model.h5
  train_data: artifacts/Data_ingestion/data/train
  validation_data: artifacts/Data_ingestion/data/valid
  
  
Model_Evaluation:
  dir: artifacts/artifaacts/model_evaluation
  test_data: artifacts\Data_ingestion\data\test
  mlflow_url: https://dagshub.com/arpanchakraborty23/MRI_Classification.mlflow
  model_path: artifacts/model_train/model.h5
  